/* run after it is already running */

INSERT INTO netflix.FILM (TITLE, GENRE, DIRECTOR, YEAR, PRICE, URL, TRAILER) VALUES ('Fast and Furious', 'Action', 'Rob Cohen', 2001, 4, 'https://www.underbrain.com/wp-content/uploads/jc_atg1.jpg','https://www.youtube.com/watch?v=2TAOizOnNPo');
INSERT INTO netflix.FILM (TITLE, GENRE, DIRECTOR, YEAR, PRICE, URL, TRAILER) VALUES ('Ice Age', 'Animation', 'Chris Wedge', 2002, 4.50,'https://pictures.abebooks.com/isbn/9781906861407-es.jpg','https://www.youtube.com/watch?v=i4noiCRJRoE');
INSERT INTO netflix.FILM (TITLE, GENRE, DIRECTOR, YEAR, PRICE, URL, TRAILER) VALUES ('Avatar', 'Sci-Fi', 'James Cameron', 2008, 5.00,'https://pics.filmaffinity.com/Avatar-208925608-mmed.jpg','https://www.youtube.com/watch?v=6ziBFh3V1aM');
INSERT INTO netflix.FILM (TITLE, GENRE, DIRECTOR, YEAR, PRICE, URL, TRAILER) VALUES ('Aladdin', 'Animation', 'Rob Cohen', 1992, 4,'https://es.web.img3.acsta.net/medias/nmedia/18/73/54/02/20415767.jpg','https://www.youtube.com/watch?v=8HrmBXgiwDU');
INSERT INTO netflix.FILM (TITLE, GENRE, DIRECTOR, YEAR, PRICE, URL, TRAILER) VALUES ('The Simpsons: The Movie', 'Animation', 'David Silverman', 2007, 4,'https://static.rogerebert.com/uploads/movie/movie_poster/the-simpsons-movie-2007/large_xUJmQfAAERB6VJRNx3TCHtr7N9s.jpg','https://www.youtube.com/watch?v=HRV6tMR-SSs');
INSERT INTO netflix.FILM (TITLE, GENRE, DIRECTOR, YEAR, PRICE, URL, TRAILER) VALUES ('Blade Runner', 'Sci-Fi', 'Ridley Scott',1982, 4,'https://2.bp.blogspot.com/-TfudXWjJ9TE/Wpt7DgPU6WI/AAAAAAAAK1M/JyYDiB8c-pE2WWUkBug-_0_6gA10r8qJwCLcBGAs/s1600/blade-runner-cartel-poster.jpg','https://www.youtube.com/watch?v=eogpIG53Cis');
INSERT INTO Netflix.FILM (TITLE, GENRE, DIRECTOR, YEAR, PRICE, URL, TRAILER) VALUES ('Space Odyssey', 'Sci-Fi', 'Stanley Kubrick', 1968, 4,'https://lh3.googleusercontent.com/proxy/V4ivA4NjLKQLg6JgmMflO2AougXsr8Er7JU53HzUifimGq1xFQrnpIKw0R2KkAuYxVnydBsl6IeCkD2VevwX7lUePArL8QJrZvcn12QKe8eIchukxBuxobZBFH2Ah6x3NTXtbndD','https://www.youtube.com/watch?v=oR_e9y-bka0');
INSERT INTO netflix.FILM (TITLE, GENRE, DIRECTOR, YEAR, PRICE, URL, TRAILER) VALUES ('Alice in Wonderland', 'Animation', 'Tim Burton', 2010, 4.50,'https://images-na.ssl-images-amazon.com/images/I/61ivGYQw6aL._SY445_.jpg','https://www.youtube.com/watch?v=9POCgSRVvf0');
INSERT INTO netflix.FILM (TITLE, GENRE, DIRECTOR, YEAR, PRICE, URL, TRAILER) VALUES ('Skyfall', 'Action', 'Sam Mendes', 2012, 5.00,'https://www.femalefirst.co.uk/image-library/port/333/s/skyfall-teaser-poster-2.jpg','https://www.youtube.com/watch?v=6kw1UVovByw');
INSERT INTO netflix.FILM (TITLE, GENRE, DIRECTOR, YEAR, PRICE, URL, TRAILER) VALUES ('John Wick', 'Action', 'Chad Stahelski', 2014, 4,'https://images-na.ssl-images-amazon.com/images/I/51-v2kovwfL._SY445_.jpg','https://www.youtube.com/watch?v=2AUmvWm5ZDQ');
INSERT INTO netflix.FILM (TITLE, GENRE, DIRECTOR, YEAR, PRICE, URL, TRAILER) VALUES ('Avengers: Infinity War', 'Action', 'Joe Russo', 2018, 6,'https://i.pinimg.com/474x/c5/ba/1e/c5ba1e0f1f6a82b9e6967eb8085ceaf9.jpg','https://www.youtube.com/watch?v=6ZfuNTqbHE8');
INSERT INTO netflix.FILM (TITLE, GENRE, DIRECTOR, YEAR, PRICE, URL, TRAILER) VALUES ('The Incredibles', 'Animation', 'Brad Bird', 2018, 4,'https://images-na.ssl-images-amazon.com/images/I/513RDYJrstL._SX342_.jpg','https://www.youtube.com/watch?v=-UaGUdNJdRQ');
INSERT INTO netflix.FILM (TITLE, GENRE, DIRECTOR, YEAR, PRICE, URL, TRAILER) VALUES ('Avengers: End Game', 'Action', 'Joe Russo', 2013, 3,'https://lh3.googleusercontent.com/LuXJCZplZKwVigsjQCipK5qUUiyW8NBHqEtAeMByuYu-QqFHzq0gSULnS-Ict6V_Pvi0','https://www.youtube.com/watch?v=TcMBFSGVi1c');
INSERT INTO netflix.FILM (TITLE, GENRE, DIRECTOR, YEAR, PRICE, URL, TRAILER) VALUES ('Toy Story', 'Animation', 'John Lasseter', 1995, 5,'https://i.pinimg.com/originals/ee/9f/21/ee9f21432dac3689d2d3100d2055f151.jpg','https://www.youtube.com/watch?v=rNk1Wi8SvNc');
INSERT INTO netflix.FILM (TITLE, GENRE, DIRECTOR, YEAR, PRICE, URL, TRAILER) VALUES ('Ex Machina', 'Sci-Fi', 'Domnhall Gleeson', 2015, 3,'https://pics.filmaffinity.com/Ex_Machina-368494509-mmed.jpg','https://www.youtube.com/watch?v=EoQuVnKhxaM');
INSERT INTO netflix.FILM (TITLE, GENRE, DIRECTOR, YEAR, PRICE, URL, TRAILER) VALUES ('Indiana Jones: Raiders of the Lost Ark', 'Action', 'Steven Spielberg', 1981, 4,'https://images-na.ssl-images-amazon.com/images/I/51K8ouYrHeL._SY445_.jpg','https://www.youtube.com/watch?v=XkkzKHCx154');
INSERT INTO netflix.FILM (TITLE, GENRE, DIRECTOR, YEAR, PRICE, URL, TRAILER) VALUES ('Matrix', 'Sci-Fi', 'Lana Wachowski', 1999, 5,'https://pics.filmaffinity.com/Matrix-155050517-mmed.jpg','https://youtube.com/watch?v=m8e-FF8MsqU');
INSERT INTO netflix.FILM (TITLE, GENRE, DIRECTOR, YEAR, PRICE, URL, TRAILER) VALUES ('Full Metal Jacket', 'Action', 'Stanley Kubrick', 1987, 3,'https://2.bp.blogspot.com/-FZidkn9jJfU/VJH4JFXaoCI/AAAAAAAAAKk/50nAzfLCNKs/s1600/Full_Metal_Jacket_poster.jpg','https://www.youtube.com/watch?v=Ks_MbPPkhmA');
INSERT INTO netflix.FILM (TITLE, GENRE, DIRECTOR, YEAR, PRICE, URL, TRAILER) VALUES ('Finding Nemo', 'Animation', 'Andrew Stanton', 2003, 4,'https://images-na.ssl-images-amazon.com/images/I/51-difUGanL.jpg','https://www.youtube.com/watch?v=wZdpNglLbt8');
INSERT INTO netflix.FILM (TITLE, GENRE, DIRECTOR, YEAR, PRICE, URL, TRAILER) VALUES ('A Clockwork Orange', 'Sci-Fi', 'Stanley Kubrick', 1971, 5,'https://vignette.wikia.nocookie.net/lossimpson/images/3/39/A_clockwork_orange.jpg/revision/latest/top-crop/width/360/height/450?cb=20130806024155&path-prefix=es','https://www.youtube.com/watch?v=SPRzm8ibDQ8');
INSERT INTO netflix.FILM (TITLE, GENRE, DIRECTOR, YEAR, PRICE, URL, TRAILER) VALUES ('How to Train Your Dragon', 'Animation', 'Chris Sanders', 2010, 3,'https://images-na.ssl-images-amazon.com/images/I/91sqZ5NyhwL._SY445_.jpg','https://www.youtube.com/watch?v=oKiYuIsPxYk');
INSERT INTO netflix.FILM (TITLE, GENRE, DIRECTOR, YEAR, PRICE, URL, TRAILER) VALUES ('Kill Bill: Part 1', 'Action', 'Quentin Tarantino', 2003, 5, 'https://images-na.ssl-images-amazon.com/images/I/51KD020QTAL._SY445_.jpg','https://www.youtube.com/watch?v=7kSuas6mRpk');
INSERT INTO netflix.FILM (TITLE, GENRE, DIRECTOR, YEAR, PRICE, URL, TRAILER) VALUES ('Interstellar', 'Sci-Fi', 'Christopher Nolan', 2014, 3,'https://upload.wikimedia.org/wikipedia/en/b/bc/Interstellar_film_poster.jpg','https://www.youtube.com/watch?v=zSWdZVtXT7E');
INSERT INTO netflix.FILM (TITLE, GENRE, DIRECTOR, YEAR, PRICE, URL, TRAILER) VALUES ('Mission Impossible', 'Action', 'Brian De Palma', 1996, 4,'https://www.covercaratulas.com/ode/mini_mini/carteles-13808.jpg','https://www.youtube.com/watch?v=Ohws8y572KE');
INSERT INTO netflix.FILM (TITLE, GENRE, DIRECTOR, YEAR, PRICE, URL, TRAILER) VALUES ('Inception', 'Sci-Fi', 'Christopher Nolan', 2010, 5,'https://is2-ssl.mzstatic.com/image/thumb/Video113/v4/83/84/eb/8384eb90-6fa0-1a28-a838-b23437efd244/pr_source.lsr/268x0w.jpg','https://www.youtube.com/watch?v=YoHD9XEInc0');
INSERT INTO netflix.FILM (TITLE, GENRE, DIRECTOR, YEAR, PRICE, URL, TRAILER) VALUES ('Stealth', 'Action', 'Rob Cohen', 2005, 3, 'https://upload.wikimedia.org/wikipedia/en/5/5a/Stealth_poster.jpg','https://www.youtube.com/watch?v=a2PW7a9ViDc');
INSERT INTO netflix.FILM (TITLE, GENRE, DIRECTOR, YEAR, PRICE, URL, TRAILER) VALUES ('Ratatouille', 'Animation', 'Brad Bird', 2007, 4,'https://lh3.googleusercontent.com/RtjcMBUV4Zw-FgLzN31ECrwpltxstIqeI5s9FSBz9SCYD0_I6EC5EXdEhJsdtFfWnxn2','https://www.youtube.com/watch?v=uVeNEbh3A4U');


INSERT INTO netflix.USER (CODE, NAME, SURNAME, PASSWORD, SALARY) VALUES ('jorge', 'Jorge', 'El Busto', 'pass', 100);